// layout.tsx

import { Inter } from 'next/font/google';
import './globals.css';
import ThemeSwitch from './components/ThemeSwitch';

// Asegúrate de que "metadata" esté fuera de la directiva "use client"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Aquí puedes colocar el ThemeSwitch */}
        <div className="absolute top-4 right-4 z-10">
          <ThemeSwitch />
        </div>

        {/* El contenido de las páginas se renderiza aquí */}
        {children}
      </body>
    </html>
  );
}



